server:
  port: 5004
spring:
  application:
    name: api-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      enabled: false
      import-check:
        enabled: false
    gateway:
      routes:
        - id: products-service
          uri: http://products-service:5001
          predicates:
            - Path=/products/**
        - id: orders-service
          uri: http://orders-service:5002
          predicates:
            - Path=/orders/**
        - id: customers-service
          uri: http://customers-service:5003
          predicates:
            - Path=/customers/**